vaadin:
  launch-browser: 'true'
logging:
  level:
    org:
      atmosphere: warn
server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://gcc180-rds.c3o6mguucr80.us-east-2.rds.amazonaws.com:5432/gcc180
    username: gcc180
    password: gV9yG74iog6Z
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update